var h,w,l,t;
var topMar = 1;
var leftMar = -2;
var space = 1;
var isvisible;
var MENU_SHADOW_COLOR='#999999';
var global = window.document
global.fo_currentMenu = null
global.fo_shadows = new Array
var menu1="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/web20/Index.html'>WEB 2.0</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/asp/Index.html'>ASP 专区</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/php/Index.html'>PHP 专区</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/jsp/Index.html'>JSP 专区</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/aspnet/Index.html'>.NET 专区</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/cgi/Index.html'>CGI 专区</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/xhtml/Index.html'>XHTML CSS</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/xml/Index.html'>XML 专区</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/script/Index.html'>Scripting</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/media/Index.html'>应用编程</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/web/soft/Index.html'>编程软件</a><br>";
var menu2="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/java/Index.html'>Java语言</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/c/Index.html'>C语言</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/cpp/Index.html'>C++语言</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/vc/Index.html'>VC编程</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/vb/Index.html'>VB编程</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/com/Index.html'>C#语言</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/delphi/Index.html'>Delphi语言</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/pb/Index.html'>PowerBuilder</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/uml/Index.html'>UML语言</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/program/hb/Index.html'>汇编语言</a><br>";
var menu3="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/ps/Index.html'>PhotoShop</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/cd/Index.html'>CorelDraw</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/fh/Index.html'>Freehand</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/fw/Index.html'>Fireworks</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/ill/Index.html'>Illustrator</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/pt/Index.html'>Painter</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/pic/pi/Index.html'>PhotoImpact</a><br>";
var menu4="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/media/author/Index.html'>Authorware</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/media/max/Index.html'>3ds Max</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/media/flash/Index.html'>Flash</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/media/maya/Index.html'>Maya</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/media/director/Index.html'>Director</a><br>";
var menu5="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/server/websrv/Index.html'>WEB服务器</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/server/ftpsrv/Index.html'>FTP服务器</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/server/mailsrv/Index.html'>Mail服务器</a><br>";
var menu6="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/access/Index.html'>Access</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/mssql/Index.html'>SQL Server</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/mysql/Index.html'>MySQL</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/oracle/Index.html'>Oracle</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/sybase/Index.html'>Sybase</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/foxpro/Index.html'>FoxPro</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/db2/Index.html'>DB2</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/database/sjkzh/Index.html'>数据库综合</a><br>";
var menu7="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/microsoft/Index.html'>微软认证</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/cisco/Index.html'>思科认证</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/oracle/Index.html'>ORACLE认证</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/java/Index.html'>JAVA认证</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/grade/Index.html'>计算机等级考试</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/it/Index.html'>资格水平考试</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/netsafe/Index.html'>网络安全</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/os/Index.html'>系统认证</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/dev/Index.html'>程序开发</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/exam/pic/Index.html'>图形图象</a><br>";
var menu8="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/net/yl/Index.html'>网络原理</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/net/router/Index.html'>路由技术</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/net/app/Index.html'>网络应用</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/net/safe/Index.html'>网络安全</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/net/fhq/Index.html'>防 火 墙</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/net/ytwl/Index.html'>以太网络</a><br>";
var menu9="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/dos/Index.html'>DOS系统</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/win2k/Index.html'>Windows 2000</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/winxp/Index.html'>Windows XP</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/win03/Index.html'>Windows 2003</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/mac/Index.html'>Mac OS X</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/linux/Index.html'>Linux</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/bsd/Index.html'>FreeBSD</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/solaris/Index.html'>Solaris</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/unix/Index.html'>SCO UNIX</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/os/aix/Index.html'>IBM AIX</a><br>";
var menu11="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/seo/alexa/Index.html'>alexa排名</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/seo/seo/Index.html'>网站优化</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/seo/search/Index.html'>搜索引擎</a><br>";
var menu12="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/soft/chat/Index.html'>聊天软件</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/soft/office/Index.html'>办公软件</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/soft/ftp/Index.html'>上传下载</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/soft/scan/Index.html'>杀毒软件</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/soft/ie/Index.html'>浏 览 器</a><br>";
var menu13="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hacker/hacker1/Index.html'>脱壳技术</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hacker/hacker2/Index.html'>反 汇 编</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hacker/hacker3/Index.html'>算法研究</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hacker/hacker4/Index.html'>原理分析</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hacker/hacker5/Index.html'>破解实例</a><br>";
var menu14="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf1/Index.html'>安全初步</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf2/Index.html'>病毒分析</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf3/Index.html'>QQ攻防</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf4/Index.html'>黑客入门</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf5/Index.html'>漏洞研究</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf6/Index.html'>黑客教程</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf7/Index.html'>工具使用</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf8/Index.html'>攻防实战</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/hkgf/hkgf9/Index.html'>黑客编程</a><br>";
var menu15="&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/game/ms/Index.html'>魔兽争霸</a><br>&nbsp;<a style=font-size:9pt;line-height:14pt; href='/edu/game/jwt/Index.html'>劲舞团</a><br>";

document.write("|<a href='/edu/Index.html'>&nbsp;学院首页&nbsp;</a>|<a href='/edu/web/Index.html' onMouseOver='ShowMenu(menu1,100)'>&nbsp;网络编程&nbsp;</a>|<a href='/edu/program/Index.html' onMouseOver='ShowMenu(menu2,100)'>&nbsp;程序设计&nbsp;</a>|<a href='/edu/pic/Index.html' onMouseOver='ShowMenu(menu3,100)'>&nbsp;图形设计&nbsp;</a>|<a href='/edu/media/Index.html' onMouseOver='ShowMenu(menu4,100)'>&nbsp;媒体动画&nbsp;</a>|<a href='/edu/server/Index.html' onMouseOver='ShowMenu(menu5,100)'>&nbsp;服务器类&nbsp;</a>|<a href='/edu/database/Index.html' onMouseOver='ShowMenu(menu6,100)'>&nbsp;数据库类&nbsp;</a>|<a href='/edu/exam/Index.html' onMouseOver='ShowMenu(menu7,100)'>&nbsp;认证考试&nbsp;</a>|<a href='/edu/net/Index.html' onMouseOver='ShowMenu(menu8,100)'>&nbsp;网络技术&nbsp;</a>|<a href='/edu/os/Index.html' onMouseOver='ShowMenu(menu9,100)'>&nbsp;操作系统&nbsp;</a>|<a href='/edu/seo/Index.html' onMouseOver='ShowMenu(menu11,100)'>&nbsp;站长兵书&nbsp;</a>|<a href='/edu/soft/Index.html' onMouseOver='ShowMenu(menu12,100)'>&nbsp;软件教学&nbsp;</a>|<a href='/edu/hacker/Index.html' onMouseOver='ShowMenu(menu13,100)'>&nbsp;软件破解&nbsp;</a>|<a href='/edu/hkgf/Index.html' onMouseOver='ShowMenu(menu14,100)'>&nbsp;黑客攻防&nbsp;</a>|<a href='/edu/game/Index.html' onMouseOver='ShowMenu(menu15,100)'>&nbsp;游戏教程&nbsp;</a>|<a href='/edu/it/Index.html'>&nbsp;IT 业界&nbsp;</a>|");