package com.loadtrend;



/**
 * TAddress generated by hbm2java
 */

public class TAddress  implements java.io.Serializable {
    
    // Fields
    private Integer id;
    private String address;
    private String zipcode;
    private String tel;
    private Integer idx;
    private TUser user;

    // Constructor
    /** default constructor */
    public TAddress() {
    }
    
    /** constructor with id */
    public TAddress(Integer id) {
        this.id = id;
    }
   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public Integer getIdx() {
        return this.idx;
    }
    
    public void setIdx(Integer idx) {
        this.idx = idx;
    }

    public TUser getUser()
    {
        return user;
    }

    public void setUser( TUser user )
    {
        this.user = user;
    }

}