package com.loadtrend;

import java.util.Set;



/**
 * TGroup generated by hbm2java
 */

public class TGroup  implements java.io.Serializable {


    // Fields    
    private Integer id;
    private String name;
    private Set users;

    // Constructors

    /** default constructor */
    public TGroup() {
    }
    
    /** constructor with id */
    public TGroup(Integer id) {
        this.id = id;
    }
   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Set getUsers()
    {
        return users;
    }

    public void setUsers( Set users )
    {
        this.users = users;
    }
}