package com.loadtrend;



/**
 * TPassport generated by hbm2java
 */

public class TPassport  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String serial;
     private Integer expiry;
     private TUser user;

    // Constructors

    /** default constructor */
    public TPassport() {
    }
    
    /** constructor with id */
    public TPassport(Integer id) {
        this.id = id;
    }
   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getSerial() {
        return this.serial;
    }
    
    public void setSerial(String serial) {
        this.serial = serial;
    }

    public Integer getExpiry() {
        return this.expiry;
    }
    
    public void setExpiry(Integer expiry) {
        this.expiry = expiry;
    }

    public TUser getUser()
    {
        return user;
    }

    public void setUser( TUser user )
    {
        this.user = user;
    }
}