package com.loadtrend;

import java.util.Set;



/**
 * TUser generated by hbm2java
 */

public class TUser  implements java.io.Serializable {


    // Fields
    private Integer id;
    private String name;
    private Integer age;
    private Integer version;
    private TPassport passport;
    private TGroup group;
    private Set addresses;

    // Constructors

    /** default constructor */
    public TUser() {
    }
    
    /** constructor with id */
    public TUser(Integer id) {
        this.id = id;
    }

    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public TPassport getPassport()
    {
        return passport;
    }

    public void setPassport( TPassport passport )
    {
        this.passport = passport;
    }

    public TGroup getGroup()
    {
        return group;
    }

    public void setGroup( TGroup group )
    {
        this.group = group;
    }

    public Set getAddresses()
    {
        return addresses;
    }

    public void setAddresses( Set addresses )
    {
        this.addresses = addresses;
    }
}